{% set name = "perl-compress-raw-zlib" %}
{% set version = "2.214" %}
{% set sha256 = "5eea0c05c7b01dc93b620f04c89176eefb5002586ca0bebae3b8c2e70920e62e" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/Compress-Raw-Zlib-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test  # [build_platform == target_platform]
    - make install VERBINST=1

requirements:
  build:
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Compress::Raw::Zlib

about:
  home: "https://metacpan.org/pod/Compress::Raw::Zlib"
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: "Basic utilities for writing tests."
  license_file:
    - {{ environ["PREFIX"] }}/lib/perl5/core_perl/pod/perlartistic.pod
    - {{ environ["PREFIX"] }}/lib/perl5/core_perl/pod/perlgpl.pod
  doc_url: "https://metacpan.org/pod/Compress::Raw::Zlib"

extra:
  recipe-maintainers:
    - cbrueffer
    - conda-forge/perl-packagers
